import { CaseStudy } from "@/types";

export const caseStudies: CaseStudy[] = [
    {
        slug: "payflow",
        company: "LocalPay",
        tagline: "Streamlined payments for local businesses",
        category: "Financial Technology",
        title: "Building a Custom Payment Portal That Processed $50K in Its First Month",
        heroImage: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2070&auto=format&fit=crop",
        logo: "",
        challenge: "LocalPay, a regional payment startup, needed a secure MVP payment processing platform tailored for local vendors. They had a tight budget and needed to hit the market quickly to secure their first round of angel funding.",
        solution: "We built a lean, secure MVP using React and Node.js with Stripe Connect integration. We focused heavily on a frictionless vendor onboarding experience and provided a clean, simple dashboard for tracking daily sales.",
        results: "The MVP launched perfectly on schedule. Within the first month, they onboarded 15 local vendors and successfully processed over $50K in community transactions with zero downtime.",
        metrics: [
            { value: "$50K", label: "Transactions Processed" },
            { value: "15", label: "Local Vendors" },
            { value: "100%", label: "Uptime" },
            { value: "6 weeks", label: "Time to Launch" },
        ],
        technologies: ["React", "Node.js", "PostgreSQL", "Stripe API"],
        testimonial: {
            quote: "Pitchin was exactly the agency we needed to get our MVP off the ground. They understood our constraints and delivered a high-quality product that helped us secure our angel round.",
            author: "Liam Rourke",
            role: "Founder, LocalPay",
        },
    },
    {
        slug: "learnly",
        company: "StudySpark",
        tagline: "Engaging learning tools for tutoring centers",
        category: "Education Technology",
        title: "Creating an Interactive Study Platform for a Regional Tutoring Center",
        heroImage: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop",
        logo: "",
        challenge: "A local chain of tutoring centers needed a digital platform to keep students engaged between physical sessions. Their existing method of emailing PDF worksheets was resulting in incredibly low completion rates.",
        solution: "We designed and developed a lightweight, mobile-friendly web app using Vue.js and Firebase. We built interactive quizzes, a simple gamified reward system, and a dashboard for tutors to track student progress instantly.",
        results: "Homework completion rates doubled within the first month of rollout. The center was able to onboard all 120 of their active students onto the platform seamlessly.",
        metrics: [
            { value: "2x", label: "Completion Rate" },
            { value: "120", label: "Active Students" },
            { value: "95%", label: "Tutor Satisfaction" },
            { value: "4 weeks", label: "Development Time" },
        ],
        technologies: ["Vue.js", "Firebase", "Tailwind CSS"],
        testimonial: {
            quote: "The platform Pitchin built has completely changed how our students interact with our material. It was affordable, fast to build, and works flawlessly.",
            author: "Sofia Andersson",
            role: "Owner, StudySpark Center",
        },
    },
    {
        slug: "vitalcare",
        company: "WellnessClinic app",
        tagline: "Simple appointment booking and reminders",
        category: "Health Technology",
        title: "A Mobile Booking App That Reduced Clinic No-Shows by 40%",
        heroImage: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?q=80&w=2070&auto=format&fit=crop",
        logo: "",
        challenge: "A boutique wellness clinic was struggling with appointment no-shows and spending too much administrative time on the phone. They needed a simple application for their patients to book, reschedule, and receive notifications.",
        solution: "We created a sleek React Native app for iOS and Android integrated with their existing scheduling software via API. We added automated SMS reminders and a clean interface for patients to manage their upcoming visits.",
        results: "The clinic saw an immediate 40% reduction in missed appointments. The front desk staff saved approximately 10 hours a week on phone calls, allowing them to focus on in-person patient care.",
        metrics: [
            { value: "40%", label: "Fewer No-Shows" },
            { value: "10 hrs", label: "Admin Time Saved/Wk" },
            { value: "300+", label: "App Downloads" },
            { value: "4.8", label: "App Store Rating" },
        ],
        technologies: ["React Native", "Node.js", "Twilio API"],
        testimonial: {
            quote: "Pitchin delivered a beautiful app that our patients actually use. It has saved our front desk so much time and practically paid for itself by eliminating no-shows.",
            author: "Dr. Priya Nair",
            role: "Lead Practitioner, WellnessClinic",
        },
    },
    {
        slug: "modastyle",
        company: "ArtisanGoods",
        tagline: "Handcrafted ceramics marketplace",
        category: "E-Commerce",
        title: "A Shopify Storefront Rebuild for a Local Artisan Brand",
        heroImage: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?q=80&w=2070&auto=format&fit=crop",
        logo: "",
        challenge: "A small ceramics studio was selling primarily through Instagram but needed a proper e-commerce presence to handle out-of-state orders. They had a limited budget and needed a site that beautifully showcased their craft.",
        solution: "We built a custom Next.js frontend connected to a basic Shopify backend. We focused completely on a stunning, image-heavy UI design that let their products shine, utilizing smooth animations and highly optimized imagery.",
        results: "The new site allowed them to launch their first major online collection, which sold out in 48 hours. Their site speed improved dramatically compared to standard Shopify templates.",
        metrics: [
            { value: "100%", label: "Collection Sold Out" },
            { value: "48 hrs", label: "Time to Sell Out" },
            { value: "1.2s", label: "Page Load Time" },
            { value: "98", label: "Lighthouse Score" },
        ],
        technologies: ["Next.js", "Shopify Buy Button", "Framer Motion", "Tailwind CSS"],
        testimonial: {
            quote: "They perfectly captured the aesthetic of our physical studio in digital form. We finally have an online store we can be proud to share.",
            author: "Isabelle Laurent",
            role: "Founder, ArtisanGoods",
        },
    },
    {
        slug: "shipswift",
        company: "CityCourier",
        tagline: "Local delivery tracking",
        category: "Logistics",
        title: "A Simple Tracking Dashboard for a Local Courier Service",
        heroImage: "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?q=80&w=2070&auto=format&fit=crop",
        logo: "",
        challenge: "A local bike messenger business with 5 riders was managing deliveries via text messages and a shared spreadsheet. They needed a simple way to assign routes and let local clients know when a package was arriving.",
        solution: "We built a very lightweight React dashboard for the dispatcher and a mobile-friendly view for the riders to check off deliveries. We added a basic public tracking link that could be automatically texted to the package recipient.",
        results: "The dispatcher was able to route 30% more packages per day without hiring more staff. Local clients loved receiving the tracking text messages, resulting in several five-star reviews for the courier company.",
        metrics: [
            { value: "30%", label: "Efficiency Increase" },
            { value: "5", label: "Riders Managed" },
            { value: "100+", label: "Daily Deliveries" },
            { value: "3 weeks", label: "Delivered In" },
        ],
        technologies: ["React", "Express UI", "MongoDB", "Mapbox API"],
        testimonial: {
            quote: "This small dashboard completely changed how our dispatching works. It's exactly what we needed—nothing overly complicated, just functional and fast.",
            author: "Marco Esposito",
            role: "Owner, CityCourier",
        },
    },
    {
        slug: "insightai",
        company: "MenuVision",
        tagline: "Smart pricing for local restaurants",
        category: "Data Analytics",
        title: "A Data Dashboard That Helped a Local Restaurant Group Increase Margins",
        heroImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
        logo: "",
        challenge: "A small restaurant group with three locations was blindly adjusting menu prices without knowing their true food costs. They had the raw data from their POS system but couldn't visualize it easily.",
        solution: "We wrote a simple Python script to clean their exported POS data and built a clean React dashboard utilizing Recharts to visualize profit margins per dish. We highlighted low-margin popular items to help them make informed pricing decisions.",
        results: "By adjusting the prices on just five popular but low-margin items based on our dashboard's insights, the restaurant group increased their overall profit margin by 8% over the next quarter.",
        metrics: [
            { value: "8%", label: "Margin Increase" },
            { value: "3", label: "Locations Analyzed" },
            { value: "5", label: "Menu Items Corrected" },
            { value: "1 week", label: "To Initial Prototype" },
        ],
        technologies: ["React", "Recharts", "Python", "Pandas"],
        testimonial: {
            quote: "Pitchin took our messy spreadsheets and turned them into a clear picture of our business. The insights we gained paid for the project in the first month.",
            author: "Yuki Tanaka",
            role: "Owner, Local Restaurant Group",
        },
    },
];

export function getCaseStudyBySlug(slug: string): CaseStudy | undefined {
    return caseStudies.find((cs) => cs.slug === slug);
}
