import { Service } from "@/types";

export const services: Service[] = [
    {
        slug: "web-development",
        title: "Web",
        subtitle: "Development",
        description: "Scalable, performant web applications built with modern frameworks and best practices.",
        longDescription: "From SaaS platforms to enterprise portals, we build web applications that scale. Our team specializes in React, Next.js, and Vue.js frontends paired with robust Node.js, Python, or Laravel backends — always optimized for performance, security, and maintainability.",
        icon: "✧",
        technologies: ["React", "Next.js", "Vue.js", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
        features: [
            "Server-side rendering & static generation",
            "Real-time features with WebSockets",
            "Authentication & authorization",
            "REST & GraphQL APIs",
            "CI/CD pipelines & DevOps",
            "Performance optimization",
        ],
        process: [
            { step: 1, title: "Discovery", description: "We map your requirements, user journeys, and technical constraints." },
            { step: 2, title: "Architecture", description: "We design the system architecture, database schema, and API contracts." },
            { step: 3, title: "Development", description: "Iterative sprints with weekly demos and continuous deployment." },
            { step: 4, title: "QA & Launch", description: "Thorough testing, performance audits, and production deployment." },
        ],
    },
    {
        slug: "mobile-development",
        title: "Mobile",
        subtitle: "Development",
        description: "Cross-platform mobile apps with native feel, built with React Native and Flutter.",
        longDescription: "We build iOS and Android applications that feel native on every platform. Using React Native, we maximize code reuse while maintaining the performance and UX quality your users expect. From MVP to App Store launch and beyond.",
        icon: "◒",
        technologies: ["React Native", "Expo", "TypeScript", "Firebase", "iOS", "Android"],
        features: [
            "Cross-platform iOS & Android",
            "Native animations & gestures",
            "Offline-first architecture",
            "Push notifications",
            "In-app purchases",
            "App Store & Play Store deployment",
        ],
        process: [
            { step: 1, title: "UX Design", description: "Platform-specific wireframes and interactive prototypes." },
            { step: 2, title: "Architecture", description: "State management, navigation, and offline data strategy." },
            { step: 3, title: "Development", description: "Feature development with weekly TestFlight/beta builds." },
            { step: 4, title: "Launch", description: "App store submission, review process management, and monitoring." },
        ],
    },
    {
        slug: "digital-marketing",
        title: "Digital",
        subtitle: "Marketing",
        description: "Data-driven marketing strategies that drive qualified traffic and convert visitors into clients.",
        longDescription: "We combine technical SEO, paid advertising, and content strategy to grow your digital presence. Our marketing team works closely with the development team to ensure your site performs technically while your campaigns perform commercially.",
        icon: "◈",
        technologies: ["Google Analytics", "SEMrush", "HubSpot", "Meta Ads", "Google Ads", "Mixpanel"],
        features: [
            "Technical SEO audits & implementation",
            "PPC campaign management",
            "Content strategy & creation",
            "Conversion rate optimization",
            "Email marketing automation",
            "Analytics & reporting dashboards",
        ],
        process: [
            { step: 1, title: "Audit", description: "Full technical and content audit to identify gaps and opportunities." },
            { step: 2, title: "Strategy", description: "Custom growth strategy aligned with your business goals." },
            { step: 3, title: "Execution", description: "Campaign launch, content production, and SEO implementation." },
            { step: 4, title: "Optimization", description: "Continuous A/B testing and performance tuning." },
        ],
    },
    {
        slug: "branding",
        title: "Brand",
        subtitle: "Strategy",
        description: "Visual identities and brand systems that make startups look like established market leaders.",
        longDescription: "A great product deserves a great brand. We create visual identities — logos, color systems, typography, and design guidelines — that communicate your values at a glance and build lasting recognition with your audience.",
        icon: "✦",
        technologies: ["Figma", "Adobe Illustrator", "Brand Guidelines", "Design Systems"],
        features: [
            "Logo design & wordmark",
            "Color palette & typography",
            "Brand guidelines document",
            "Marketing collateral",
            "Pitch deck design",
            "Social media templates",
        ],
        process: [
            { step: 1, title: "Discovery", description: "Brand workshops exploring your vision, audience, and competitors." },
            { step: 2, title: "Concepts", description: "Three distinct creative directions presented for feedback." },
            { step: 3, title: "Refinement", description: "Selected direction refined to pixel perfection." },
            { step: 4, title: "Delivery", description: "Complete brand kit in all formats, ready for any medium." },
        ],
    },
    {
        slug: "ui-ux-design",
        title: "UI/UX",
        subtitle: "Design",
        description: "Research-driven interfaces that reduce friction and increase the metrics that matter.",
        longDescription: "Great design is not decoration — it is strategy. Our UX team combines user research, information architecture, and visual design to create experiences that delight users and drive business outcomes.",
        icon: "◎",
        technologies: ["Figma", "Maze", "Hotjar", "UserTesting", "Lottie", "Framer"],
        features: [
            "User research & personas",
            "Information architecture",
            "Wireframes & prototypes",
            "UI design & design systems",
            "Usability testing",
            "Design-to-dev handoff",
        ],
        process: [
            { step: 1, title: "Research", description: "User interviews, competitive analysis, and journey mapping." },
            { step: 2, title: "Wireframes", description: "Low-fidelity flows validated with real users before visual design." },
            { step: 3, title: "UI Design", description: "High-fidelity screens with interactive Figma prototypes." },
            { step: 4, title: "Handoff", description: "Developer-ready specs with accessible components and animations." },
        ],
    },
    {
        slug: "cloud-services",
        title: "Cloud",
        subtitle: "Services",
        description: "Infrastructure design, DevOps implementation, and cloud migration for growing teams.",
        longDescription: "Whether you are migrating from on-premise, optimizing a spiraling AWS bill, or setting up CI/CD from scratch, our cloud engineers bring deep expertise in AWS, GCP, and Azure to keep your infrastructure reliable, secure, and cost-efficient.",
        icon: "☁︎",
        technologies: ["AWS", "GCP", "Terraform", "Docker", "Kubernetes", "GitHub Actions"],
        features: [
            "Cloud architecture design",
            "AWS / GCP / Azure setup",
            "CI/CD pipeline implementation",
            "Container orchestration (K8s)",
            "Cost optimization",
            "Security & compliance audits",
        ],
        process: [
            { step: 1, title: "Assessment", description: "Current infrastructure audit and cost analysis." },
            { step: 2, title: "Planning", description: "Target architecture design and migration roadmap." },
            { step: 3, title: "Migration", description: "Zero-downtime migration with rollback plans at every stage." },
            { step: 4, title: "Handover", description: "Documentation, runbooks, and team training." },
        ],
    },
];

export function getServiceBySlug(slug: string): Service | undefined {
    return services.find((s) => s.slug === slug);
}
